services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${PG_DB}'
      - 'POSTGRES_PASSWORD=${PG_PASSWORD}'
      - 'POSTGRES_USER=${PG_USER}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mapnet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${PG_DB}'
      - 'SPRING_DATASOURCE_USERNAME=${PG_USER}'
      - 'SPRING_DATASOURCE_PASSWORD=${PG_PASSWORD}'
      - 'ADMIN_USERNAME=${ADMIN_USER}'
      - 'ADMIN_PASSWORD=${ADMIN_PASSWORD}'
      - 'JWT_SECRET=${JWT_SECRET}'
      - 'JWT_EXPIRATION=${JWT_EXPIRE}'
      - 'APP_MODE=${MODE}'
    networks:
      - mapnet
volumes:
  postgres_data:

networks:
  mapnet:
    driver: bridge
