services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mininuniver'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=Admin'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Admin -d mininuniver"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mininuniver'
      - 'SPRING_DATASOURCE_USERNAME=Admin'
      - 'SPRING_DATASOURCE_PASSWORD=admin'
      - 'ADMIN_USERNAME=admin'
      - 'ADMIN_PASSWORD=secret_password'
      - 'JWT_SECRET=verySecureKeyForJwtTokenSigningInDockerEnvironment'
      - 'JWT_EXPIRATION=86400000'

volumes:
  postgres_data: